# Docker Compose 파일의 버전을 지정
# '3.8'은 Docker Compose 버전 3.8을 사용한다는 뜻
# Docker 엔진 19.03.0 이상과 호환되며, 최신 기능 지원
version: '3.8'

# 서비스 정의 시작
# 'services' 아래에 컨테이너(서비스) 설정을 나열
services:
  # 'reader'라는 이름의 서비스(컨테이너)를 정의
  # 이 이름은 Docker Compose가 이 서비스를 구분할 때 사용
  reader:
    # 컨테이너의 고정된 이름을 'reader'로 설정
    # 기본적으로 Docker는 랜덤 이름을 붙이는데, 이걸로 명시적으로 지정
    container_name: reader

    # 컨테이너를 빌드하는 방법 정의
    build:
      # 빌드에 사용할 파일이 있는 위치(컨텍스트)를 현재 디렉터리로 설정
      # '.'은 'docker-compose.yml'이 있는 폴더를 의미
      context: .

      # 사용할 Dockerfile의 경로 지정
      # 현재 디렉터리에 있는 'Dockerfile'을 사용해 컨테이너 빌드
      dockerfile: ./Dockerfile

    # 컨테이너 재시작 정책 설정
    # 'always'는 컨테이너가 꺼지면(에러나 재부팅 등) 자동으로 다시 시작
    # 서비스가 항상 실행 중이어야 할 때 유용
    restart: always

    # 호스트와 컨테이너 간 포트 매핑 설정
    ports:
      # '3000:3000'은 호스트의 3000번 포트를 컨테이너의 3000번 포트에 연결
      # 예: localhost:3000으로 접속하면 컨테이너의 3000번 포트로 감
      # Next.js 앱은 기본적으로 3000번 포트를 사용
      - 3000:3000

    # 환경 변수 파일 지정
    env_file:
      # './apps/reader/.env.local' 파일에서 환경 변수를 읽어 컨테이너에 전달
      # 예: 데이터베이스 URL, API 키 같은 설정을 이 파일에 넣음
      # Next.js에서 로컬 환경 변수로 자주 사용되는 파일명
      - ./apps/reader/.env.local
